version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "gradle"
    directory: "/gateway"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "gradle"
    directory: "/e2e-tests"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "npm"
    directory: "/e2e-tests/docker/subgraphs/products"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14

  - package-ecosystem: "npm"
    directory: "/e2e-tests/docker/subgraphs/reviews"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
      semver-major-days: 14

  - package-ecosystem: "docker"
    directory: "/gateway/app"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/e2e-tests/docker/feddi-gateway"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/e2e-tests/docker/subgraphs/products"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker"
    directory: "/e2e-tests/docker/subgraphs/reviews"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7

  - package-ecosystem: "docker-compose"
    directory: "/e2e-tests/docker"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 7
