package dev.feddi.federation.engine.compose;

import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import dev.feddi.federation.engine.testcase.SchemaDefinition;
import dev.feddi.federation.engine.testcase.SupergraphExpectation;
import dev.feddi.federation.engine.testcase.TestCaseLoader;
import graphql.language.Document;
import graphql.parser.Parser;
import graphql.schema.GraphQLSchema;
import graphql.schema.idl.SchemaPrinter;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Stream;

import static org.assertj.core.api.Assertions.assertThat;

/**
 * Test runner for supergraph composition verification.
 * 
 * Verifies that the supergraph generated by the Composer matches
 * the expected supergraph defined in schema.yaml files.
 */
class SuperGraphTest {

    private static final Logger log = LoggerFactory.getLogger(SuperGraphTest.class);

    private static TestCaseLoader loader;
    private static Composer composer;
    private static SchemaPrinter schemaPrinter;
    private static Parser parser;
    private static ObjectMapper yamlMapper;
    
    @BeforeAll
    static void setUp() {
        loader = new TestCaseLoader();
        composer = new Composer();
        // Configure SchemaPrinter to produce comparable output
        schemaPrinter = new SchemaPrinter(SchemaPrinter.Options.defaultOptions()
            .includeDirectives(false)
            .includeDirectiveDefinitions(false)
            .includeScalarTypes(false)
            .includeSchemaDefinition(false));
        parser = new Parser();
        yamlMapper = new ObjectMapper(new YAMLFactory());
    }
    
    @TestFactory
    @DisplayName("Supergraph Composition Tests")
    Stream<DynamicTest> testSupergraphComposition() throws IOException, URISyntaxException {
        URL schemasUrl = getClass().getClassLoader().getResource("schemas");
        if (schemasUrl == null) {
            return Stream.empty();
        }
        
        Path schemasDir = Paths.get(schemasUrl.toURI());
        List<DynamicTest> tests = new ArrayList<>();
        
        Files.list(schemasDir)
            .filter(Files::isDirectory)
            .sorted()
            .forEach(schemaDir -> {
                try {
                    Path schemaFile = schemaDir.resolve("schema.yaml");
                    if (!Files.exists(schemaFile)) {
                        return;
                    }
                    
                    // Check if test is marked as skipped
                    JsonNode root = yamlMapper.readTree(schemaFile.toFile());
                    if (root.path("skip").asBoolean(false)) {
                        log.info("SKIPPED: {} (skip: true in schema.yaml)", schemaDir.getFileName());
                        return;
                    }

                    // Load the supergraph expectation
                    SupergraphExpectation expectation = loader.loadSupergraphExpectation(schemaFile);
                    if (expectation == null) {
                        // No supergraph expectation defined, skip
                        return;
                    }

                    // Load the schema definition to get subgraphs
                    SchemaDefinition schema = loader.loadSchema(schemaFile);
                    String testName = schemaDir.getFileName().toString();
                    
                    tests.add(DynamicTest.dynamicTest(
                        testName + ": " + schema.name(),
                        () -> verifySupergraph(schema, expectation)
                    ));
                    
                } catch (IOException e) {
                    throw new RuntimeException("Failed to load schema: " + schemaDir, e);
                }
            });
        
        return tests.stream();
    }
    
    private void verifySupergraph(SchemaDefinition schema, SupergraphExpectation expectation) {
        log.info("Verifying supergraph for: {}", schema.name());

        // Generate the supergraph using the Composer
        List<Subgraph> subgraphs = schema.subgraphs();
        CompositionResult result = composer.compose(subgraphs, true);

        if (!result.isSuccess()) {
            log.warn("Composition failed with errors:");
            result.validationResult().errors().forEach(error ->
                log.warn("  - {}: {}", error.code(), error.message()));
        }
        
        assertThat(result.isSuccess())
            .as("Composition should succeed")
            .isTrue();
        
        GraphQLSchema generatedSupergraph = result.supergraph();
        assertThat(generatedSupergraph)
            .as("Supergraph should not be null")
            .isNotNull();
        
        // Print the generated supergraph
        String actualSdl = schemaPrinter.print(generatedSupergraph);
        
        // Parse and print the expected supergraph for normalized comparison
        Document expectedDocument = parser.parseDocument(expectation.sdl());
        String expectedSdl = schemaPrinter.print(expectedDocument);
        
        log.debug("Expected supergraph:\n{}", expectedSdl);
        log.debug("Actual supergraph:\n{}", actualSdl);

        // Compare the normalized SDL strings
        assertThat(normalizeSchema(actualSdl))
            .as("Supergraph should match expected schema")
            .isEqualTo(normalizeSchema(expectedSdl));

        log.debug("  PASSED");
    }
    
    /**
     * Normalizes a schema SDL by sorting types and removing extra whitespace
     * for consistent comparison.
     */
    private String normalizeSchema(String sdl) {
        // Parse and re-print to normalize formatting
        Document doc = parser.parseDocument(sdl);
        return schemaPrinter.print(doc)
            .replaceAll("\\s+", " ")
            .trim();
    }
}
